name: CoapAirPurifier2MQTT
version: "2.0.2"
slug: coap-air-purifier-2-mqtt
description: CoapAirPurifier2MQTT is a lightweight bridge that connects Air Purifiers using the CoAP protocol to MQTT
url: https://github.com/adamcsk1/ha-airpurifier-coap
startup: services
boot: auto
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_network: true
map:
  - config
  - data
options: {}
schema: {}
